<a href="https://colab.research.google.com/github/BALAJIKUMARAN-CS/pythonNotes/blob/main/pythonNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Notes by BALAJIKUMARAN CS**

#**Numpy:**

    1. Numpy Definition

    2. How to import Numpy

    3. How to check the version

    4. Array Creation

    5. np.zeros()

    6. np.ones()

    7. np.empty()
    
    8. np.eye()

    9. np.arange()

    10. np.reshape()

    11. np.ones_like()

    12. Elipsis

    13. Printing Large Arrays without elipsis

    14. Basic operation

    15. Rules to perform operation

    16. array and integer/float

    17. multiDimensional array operations

    18. np.dot()

    19. Aggregate Functions

    20. sum(axis = 0) and sum(axis =1)

    21. Universal functions

    22. Index and slicing

    23. Array Iterating

    24. flatten()

    25. nditer()

    26. ravel()

# 1. Numpy Definition:

    NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

    This behavior is called locality of reference in computer science.

    This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

#2. How to Import Numpy

    Steps to import numpy
    ---------------------

    If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

    1. Install it using this command:

    ----- pip install numpy -------

    2. Once NumPy is installed, import it in your applications by adding the import keyword:

    ---- import numpy ----

    3. NumPy is usually imported under the np alias.

    alias: In Python alias are an alternate name for referring to the same thing.

    Create an alias with the as keyword while importing:

    ----- import numpy as np -----

    Now the NumPy package can be referred to as np instead of numpy.



In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

#3. How to check the version

    The version string is stored under __version__ attribute.



In [ ]:
print(np.__version__)

1.22.4


#4. Array Creation

    NumPy is used to work with arrays.
    
    The array object in NumPy is called ndarray.

    We can create a NumPy ndarray object by using the array() function.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr)) #type(): This built-in Python function tells us the type of the object passed to it.

[1 2 3 4 5]
<class 'numpy.ndarray'>


#5. np.zeros()

    The numpy.zeros() function returns a new array of given shape and type, with zeros.

    ----------------------------------------------
    Syntax:

    numpy.zeros(shape, dtype = None, order = 'C')
    ----------------------------------------------

    shape : integer or sequence of integers
    

    order  : C_contiguous or F_contiguous
         
         1. C-contiguous order in memory(last index varies the fastest)
            
            C order means that operating row-rise on the array will be slightly quicker

         2. FORTRAN-contiguous order in memory (first index varies the fastest).
         
            F order means that column-wise operations will be faster.


    dtype : [optional, float(byDeafult)] Data type of returned array.

In [ ]:
#simple code with only shape --

# In the below code 2 means array with 2 colums filles with zeros

# Here we are not mentioning the dtype. so it will consider dtype as float

checkZeroBasic=np.zeros((2))

print(f"{checkZeroBasic}\n")

print("The type is ",type(checkZeroBasic[1]))

[0. 0.]

The type is  <class 'numpy.float64'>


In [2]:
#simple code with only shape --

# In the below code (2,3) means array with 2 rows and 3 colum filling with zero

# Here we are not mentioning the dtype. so it will consider dtype as float
import numpy as np

checkZero=np.zeros((2,3))

print(checkZero)

print(type(checkZero[1][1]))

checkZero

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.float64'>


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#simple code with only shape and dtype--

# In the below code (2,3) means array with 2 rows and 3 colum filling with zero

# Here we are mentioning the dtype as int. so it will consider dtype as int

checkZeroWithDtype=np.zeros((2,3), dtype=np.int32)

print(checkZeroWithDtype,"\n")

print(type(checkZeroWithDtype[1][1]),"\n")

checkZeroWithDtype

[[0 0 0]
 [0 0 0]] 

<class 'numpy.int32'> 



array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

# 6. np.ones()

    The numpy.zeros() function returns a new array of given shape and type, with ones.

    ----------------------------------------------
    Syntax:

    numpy.zeros(shape, dtype = None, order = 'C')
    ----------------------------------------------

    shape : integer or sequence of integers


    order  : C_contiguous or F_contiguous

        1. C-contiguous order in memory(last index varies the fastest)

            C order means that operating row-rise on the array will be slightly quicker

        2. FORTRAN-contiguous order in memory (first index varies the fastest).

            F order means that column-wise operations will be faster.


    dtype : [optional, float(byDeafult)] Data type of returned array.

In [ ]:
#simple code with only shape --

# In the below code 2 means array with 2 colums filles with ones

# Here we are not mentioning the dtype. so it will consider dtype as float

checkOneBasic=np.ones((2))

print(f"{checkOneBasic}\n")

print("The type is ",type(checkOneBasic[1]))

[1. 1.]

The type is  <class 'numpy.float64'>


In [ ]:
#simple code with only shape --

# In the below code (2,3) means array with 2 rows and 3 colum filling with ones

# Here we are not mentioning the dtype. so it will consider dtype as float

checkOne=np.ones((2,3))

print(f"{checkOne}\n")

print("The type is ",type(checkOne[1][1]))

[[1. 1. 1.]
 [1. 1. 1.]]

The type is  <class 'numpy.float64'>


In [ ]:
#simple code with only shape and dtype--

# In the below code (2,3) means array with 2 rows and 3 colum filling with zero

# Here we are mentioning the dtype as int. so it will consider dtype as int

checkOneWithDtype=np.zeros((2,3), dtype=np.int32)

print(f"{checkOneWithDtype}\n")

print("The type is ",type(checkOne[1][1]),"\n")

checkZeroWithDtype

[[0 0 0]
 [0 0 0]]

The type is  <class 'numpy.float64'> 



array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

# 7. np.empty()

    The elements of this array will not be initialized to any value.

    It is typically used for large arrays when performance is critical, and the values will be filled in later.

    Uses:
    -------------------------
    1. This operation will run quicker that any of the array initialization functions.
    
    2. However the elements of the array will need to be explicitly set at later point

In [ ]:
#Eg 1: It will assign random values to the array Eg:2.46471327e-316

checkEmptyBasic=np.empty((2))

print(f"{checkEmptyBasic}\n")

print("The type is ",type(checkEmptyBasic[1]))

[2.46471327e-316 1.26480805e-321]

The type is  <class 'numpy.float64'>


In [ ]:
#Eg 2:

checkEmpty=np.empty((4,4))

print(f"{checkEmpty}\n")

print("The type is ",type(checkEmpty[1][1]))

[[3.53930368e-316 0.00000000e+000 2.41907520e-312 2.37663529e-312]
 [2.22809558e-312 2.46151512e-312 6.79038654e-313 2.35541533e-312]
 [2.46151512e-312 6.79038654e-313 2.35541533e-312 6.79038654e-313]
 [2.14321575e-312 2.22809558e-312 2.14321575e-312 6.94614102e-310]]

The type is  <class 'numpy.float64'>


In [ ]:
#Eg 3:
# Must Know --> Here the values of Empty array are not random values. Because We have a value for 5,5 shape already present in the memory,
# So, it takes/points to that value

checkOneTest=np.ones((5,5))

print(f"The values of Ones are {checkOneTest}\n")

checkEmptyTest=np.empty((5,5))

print(f"The values of Empty are {checkEmptyTest}\n")

The values of Ones are [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

The values of Empty are [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



#8. np.eye()

    The numpy.eye() function returns a square identity matrix of the specified size

    The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere.

    ---------------------------------------------------------------------------
    Syntax:

    numpy.eye(R, C = None, k = 0, dtype = type <‘float’>)

    --------------------------------------------------------------------------

    R : Number of rows

    C : [optional] Number of columns; By default it takes the no of rows value to column

    k : [int, optional, 0 by default]
              Diagonal we require; k>0 means diagonal above main diagonal or vice versa.

    dtype : [optional, float(by Default)] Data type of returned array.

In [4]:
#Eg 1: with only rows

checkEye=np.eye(4)

print(checkEye)

print(f"The type is {type(checkEye[1][1])}")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
The type is <class 'numpy.float64'>


In [ ]:
#Eg 2: with only rows and column

checkEyeWithRowColumn=np.eye(4,5)

print(checkEyeWithRowColumn)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:
#Eg 3: with row, column and dtype

checkEyeWithInt=np.eye(4,5,dtype=np.int32)

print(checkEyeWithInt)

print(f"The type is {type(checkEyeWithInt[1][1])}")

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [6]:
#Eg 4: with row, column, k (positive value) and dtype

"""It will move the 1 right to left based on the k value)"""

checkEyeWithK=np.eye(4,5,k=1,dtype=np.int32)

print(checkEyeWithK)


[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
#Eg 5: with row, column, k (negative value) and dtype

"""It will move the 1 up to down based on the k value)"""

checkEyeWithKneg=np.eye(4,5,k=-1,dtype=np.int32)

print(checkEyeWithKneg)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


#9. np.arange()

    The arange() function returns an array with evenly spaced elements as per the interval.
    
    The interval mentioned is half-opened i.e. [Start, Stop)

    ---------------------------------------------------------------------------
    Syntax:

    arange([start,] stop[, step,][, dtype])

    --------------------------------------------------------------------------


    start : [optional] start of interval range. By default start = 0
  
    stop  : end of interval range

    step  : [optional] step size of interval. It can be float value also
    
    By default step size = 1,  
    
    dtype : type of output array. The type will be based on input given

In [ ]:
#Eg 1: Only with stop

arangeTest=np.arange(10)

print(arangeTest)

print(f"\nThe default data type is {type(arangeTest[1])}")

[0 1 2 3 4 5 6 7 8 9]

The default data type is <class 'numpy.int64'>


In [ ]:
#Eg 2: With start and stop

arangeTestStart=np.arange(10,20)

print(arangeTestStart)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
#Eg 3: With start, stop and step

arangeTestStep=np.arange(10,20,3)

print(arangeTestStep)

[10 13 16 19]


In [ ]:
#Eg 4: With start, stop and step with float

arangeTestStepFloat=np.arange(1,5,1.1)

print(arangeTestStepFloat)

[1.  2.1 3.2 4.3]


In [ ]:
#Eg 5: With start, stop and step, dtype

arangedTypeFloat=np.arange(1,10,1,dtype=np.float64)

print(f"The values are {arangedTypeFloat} \n\n The data type of the values are {type(arangedTypeFloat[1])} ")

The values are [1. 2. 3. 4. 5. 6. 7. 8. 9.] 

 The data type of the values are <class 'numpy.float64'> 


#10. np.reshape()

    The numpy.reshape() function shapes an array without changing the data of the array.

    -------------------------------------------------------------------------
    
    Syntax:

    numpy.reshape(array, shape, order = 'C')

    -------------------------------------------------------------------------

    Points to note:

    If we have 10 elements means,
    
    numpy.reshape(4, 8) is wrong. The array needs to have the right number of elements in order to be reordered into a specified shape. Otherwise it will throw an error
    
    we can do numpy.reshape(2, 5) or (5, 2)


In [8]:
#Eg 1:

reshapeTest=np.arange(10).reshape(2,5)

print(reshapeTest)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#Eg 1:

reshapeTestErr=np.arange(10).reshape(2,10)

print(reshapeTestErr)

ValueError: ignored

#11. np.ones_like()

    This function is slightly different from numpy.ones().
    
    Instead of taking a shape this function takes an array a, and returns the new array of ones of given shape and type as given array.



In [9]:
OnesTest=np.ones((2,2))
print(f"The value of Ones is \n{OnesTest}\nThe type is {type(OnesTest)}")

OnesLikeTest=np.ones_like((OnesTest))
print(f"\nThe value of OnesLikeTest is \n{OnesLikeTest}\nThe type is {type(OnesLikeTest)}")

The value of Ones is 
[[1. 1.]
 [1. 1.]]
The type is <class 'numpy.ndarray'>

The value of OnesLikeTest is 
[[1. 1.]
 [1. 1.]]
The type is <class 'numpy.ndarray'>


#12. Elipsis

    The Ellipsis or Ellipsis literal ... (three dots) is a built-in singleton object representing an infinite or unspecified number of arguments.

In [ ]:
#Elipsis on 1D array

testElipsis = np.arange(20000)

print(testElipsis)

"""
Here the output will be

 [    0     1     2 ... 19997 19998 19999]

 We notice that all elements are not visible, But in fact these three dots, which are also referred as an ellipsis

"""
print()

[    0     1     2 ... 19997 19998 19999]



In [ ]:
#Elipsis on 2D array

testElipsis2D = np.arange(20000).reshape(100,200)

print(testElipsis2D)


[[    0     1     2 ...   197   198   199]
 [  200   201   202 ...   397   398   399]
 [  400   401   402 ...   597   598   599]
 ...
 [19400 19401 19402 ... 19597 19598 19599]
 [19600 19601 19602 ... 19797 19798 19799]
 [19800 19801 19802 ... 19997 19998 19999]]


#13. Printing Large Arrays without elipsis

    How to print all the values,

    For this we can use: set_printoptions

    -------------------------------------------------------------------------
    
    import sys
    numpy.set_printoptions(threshold=sys.maxsize)

    -------------------------------------------------------------------------

    It allows us to specify how floating point numbers, arrays and other NumPy objects are displayed.
    
    We call this function by passing in a value for the threshold argument, which sets the number of array elements for which ellipsis would begin to be used.

    The default value of threshold is 1000

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize)

testPrintArray = np.arange(2000)

print(testPrintArray)


[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

#14. Basic operation

    we can able to perform operation in numpy like

    addition

    subtraction

    multiplication

    division

    modulo

    Boolean

    etc..

In [ ]:
import numpy as np
array1=np.array([2,3,7,5])
array2=np.array([2,3,4,5])

print(f"The addition of {array1} and {array2} is {array1+array2}")
print()
print(f"The subtraction of {array1} and {array2} is {array1-array2}")
print()
print(f"The division of {array1} and {array2} is {array1/array2}")
print()
print(f"The floor division of {array1} and {array2} is {array1//array2}")
print()
print(f"The modulo of {array1} and {array2} is {array1%array2}")
print()
print(f"The Boolean of {array1} and {array2} is {array1>array2}")

The addition of [2 3 7 5] and [2 3 4 5] is [ 4  6 11 10]

The subtraction of [2 3 7 5] and [2 3 4 5] is [0 0 3 0]

The division of [2 3 7 5] and [2 3 4 5] is [1.   1.   1.75 1.  ]

The floor division of [2 3 7 5] and [2 3 4 5] is [1 1 1 1]

The modulo of [2 3 7 5] and [2 3 4 5] is [0 0 3 0]

The Boolean of [2 3 7 5] and [2 3 4 5] is [False False  True False]


#15. Rules to perform operation

    If shape of two arrays are not same,
    
    that is arr1.shape != arr2.shape,
    
    they must be broadcastable to a common shape
    
    (which may be the shape of one or the other).

In [ ]:
#The below code throws an error. Because The shapes are different

array3=np.array([2,3,4])

array4=np.array([5,6])

add=array3+array4

ValueError: ignored

#16. array and integer/float

    We can add an integer or float with an array.

    Eg:

    array=[1,2,3,4,5]
    num=1
    array+num=[2,3,4,5,6] --> it will add the number with each elements in the array

    The same is applicable for addition, subtraction, division ...etc

In [ ]:
array5=np.array([2,3,4])

number=1

print(f"The addition of {array5} and {number} is {array5+number}")
print()
print(f"The subtraction of {array5} and {number} is {array5-number}")
print()
print(f"The division of {array5} and {number} is {array5/number}")
print()
print(f"The floor division of {array5} and {number} is {array5//number}")
print()
print(f"The modulo of {array5} and {number} is {array5%number}")
print()
print(f"The Boolean of {array5} and {number} is {array5>number}")

The addition of [2 3 4] and 1 is [3 4 5]

The subtraction of [2 3 4] and 1 is [1 2 3]

The division of [2 3 4] and 1 is [2. 3. 4.]

The floor division of [2 3 4] and 1 is [2 3 4]

The modulo of [2 3 4] and 1 is [0 0 0]

The Boolean of [2 3 4] and 1 is [ True  True  True]


#17. multiDimensional array operations

    We can perform add, mul, sub,..etc in multi dimensional array also.

    The rules is as same as one dimensional array

In [ ]:
#Eg :array + array
import numpy as np
array1=np.array([[2,2],[3,3]])
array2=np.array([[2,2],[3,3]])

array1+array2


array([[4, 4],
       [6, 6]])

In [ ]:
#Eg :array + int/float
import numpy as np
multiDims=np.array([[2,2],[3,3]])
val=2.1

multiDims+val


array([[4.1, 4.1],
       [5.1, 5.1]])

#18. np.dot()

    This function returns the dot product of two arrays.
    
    For 2-D vectors, it is the equivalent to matrix multiplication.
    
    For 1-D arrays, it is the inner product of the vectors.
    
    For N-dimensional arrays, it is a sum product over the last axis of a and the second-last axis of b.

    Eg:
    a = np.array([[1,2],[3,4]])
    b = np.array([[11,12],[13,14]])

    The output will be calculated as
    
    [ [1 * 11 + 2 * 13, 1 * 12 + 2 * 14] ,[3 * 11 + 4 * 13, 3 * 12 + 4 * 14] ]


In [ ]:
#Eg: dot with one dimensional

import numpy as np

a = np.array([1,2])

b = np.array([13,14])

print(np.dot(a,b)) # np.dot(a,b)

print(a.dot(b)) #another way of using dot function

41
41


In [ ]:
#Eg: dot with two dimensional

import numpy as np

a = np.array([[1,2],[3,4]])

b = np.array([[11,12],[13,14]])

print(np.dot(a,b))

[[37 40]
 [85 92]]


#19. Aggregate Functions

    In the Python numpy module, we have many aggregate functions or statistical functions to work with a single-dim or multi-dim array.
    
    The Python numpy aggregate functions are sum, min, max, mean, average, product, median

In [ ]:
#Eg : Aggregate function with 1D array

import numpy as np

testSum=np.array([1,2,3,4,5])

print(f"The sum of the array {testSum} is {np.sum(testSum)}")
print()

print(f"The min of the array {testSum} is {np.min(testSum)}")
print()

print(f"The max of the array {testSum} is {np.max(testSum)}")
print()

print(f"The average of the array {testSum} is {np.average(testSum)}")
print()

print(f"The mean of the array {testSum} is {np.mean(testSum)}")
print()

print(f"The median of the array {testSum} is {np.median(testSum)}")
print()




The sum of the array [1 2 3 4 5] is 15

The min of the array [1 2 3 4 5] is 1

The max of the array [1 2 3 4 5] is 5

The average of the array [1 2 3 4 5] is 3.0

The mean of the array [1 2 3 4 5] is 3.0

The median of the array [1 2 3 4 5] is 3.0



In [ ]:
#Eg : Aggregate function with 1D array

import numpy as np

testSum=np.arange(6)

print(f"The sum of the array {testSum} is {np.sum(testSum)}")
print()

print(f"The min of the array {testSum} is {np.min(testSum)}")
print()

print(f"The max of the array {testSum} is {np.max(testSum)}")
print()

print(f"The average of the array {testSum} is {np.average(testSum)}")
print()

print(f"The mean of the array {testSum} is {np.mean(testSum)}")
print()

print(f"The median of the array {testSum} is {np.median(testSum)}")
print()



The sum of the array [0 1 2 3 4 5] is 15

The min of the array [0 1 2 3 4 5] is 0

The max of the array [0 1 2 3 4 5] is 5

The average of the array [0 1 2 3 4 5] is 2.5

The mean of the array [0 1 2 3 4 5] is 2.5

The median of the array [0 1 2 3 4 5] is 2.5



In [ ]:
#Eg : Aggregate function with 2D array

import numpy as np

test2D=np.arange(4).reshape(2,2)

print(f"The sum of the array {test2D} is {np.sum(test2D)}")
print()

print(f"The min of the array {test2D} is {np.min(test2D)}")
print()


The sum of the array [[0 1]
 [2 3]] is 6

The min of the array [[0 1]
 [2 3]] is 0



#20. sum(axis = 0) and sum(axis =1)

    In two dimensional array, the sum(axis = 0) and sum(axis=1) help us to sum up across the individual dimensions.

    To do that, we simply pass along a value for the axis argument.

    -----------------------------------------------------------------------------------------------------------------------
    If sum(axis = 0) --> all the values are summed up for each of the column    
                        and the result is a one dims array whose size corresponds to the number of rows in the array.
                        (simply Sums up the values in each of the column)
    

     If sum(axis = 1) --> Sums up the values in each of the rows in the array.
                          This will return an array with the sum of each row, and the size will correspond to the number of column)


    -----------------------------------------------------------------------------------------------------------------------

    Points to Note
    ---------------

    1. We can perform aggregation for individual dimensions, even using the other aggregate functions such as min, max, mean, median, etc..

In [ ]:
import numpy as np

testAxis =np.arange(4).reshape(2,2)

print(testAxis)

print(f"\n The sum of each of the column in an array is {testAxis.sum(axis=0)}")

print(f"\n The sum of each of the row in an array is {testAxis.sum(axis=1)}")

[[0 1]
 [2 3]]

 The sum of each of the column in an array is [2 4]

 The sum of each of the row in an array is [1 5]


#21. Universal functions

    Universal functions in Numpy are simple mathematical functions.
    
    It is just a term that we gave to mathematical functions in the Numpy library.
    
    Numpy provides various universal functions that cover a wide variety of operations.
    
    These functions include
    
        1. standard trigonometric functions,
        
        2. functions for arithmetic operations,
        
        3. handling complex numbers,
        
        4. statistical functions,
        
        5. etc.............

    -------------------------------------------------------------------------------------------------------------------

    Some of the universal functions are:

    1. sin, cos, tan	         -----> compute sine, cosine and tangent of angles
    
    2. arcsin, arccos, arctan	-----> calculate inverse sine, cosine and tangent
    
    3. exp                       -----> calculate the exponential of all elements in the input array.

    4. sqrt                      -----> calculate the square root of all elements in the input array.

    5. median                    -----> calculate the median of all elements in the input array.


In [ ]:
import numpy as np
testUniversal = np.array([30,60,90,120])

print(f"The values of the array are {testUniversal}\n")

print(f"The sine values of the array are {np.sin(testUniversal)}\n")

print(f"The cos values of the array are {np.cos(testUniversal)}\n")

print(f"The tan values of the array are {np.tan(testUniversal)}\n")

print(f"The square root values of the array are {np.sqrt(testUniversal)}\n")

print(f"The exponential values of the array are {np.exp(testUniversal)}\n")

The values of the array are [ 30  60  90 120]

The sine values of the array are [-0.98803162 -0.30481062  0.89399666  0.58061118]

The cos values of the array are [ 0.15425145 -0.95241298 -0.44807362  0.81418097]

The tan values of the array are [-6.4053312   0.32004039 -1.99520041  0.71312301]

The square root values of the array are [ 5.47722558  7.74596669  9.48683298 10.95445115]

The exponential values of the array are [1.06864746e+13 1.14200739e+26 1.22040329e+39 1.30418088e+52]



#22. Index and slicing

    The index and slicing of array is as same as python lists index and slicing

    Indexing:
    ---------
    Array indexing is the same as accessing an array element.

    You can access an array element by referring to its index number.

    ----------------------------------------------------------------------------------------
    
    Slicing:
    --------

    Slicing in python means taking elements from one given index to another given index.

    We pass slice instead of index like this: [start:end].

    We can also define the step, like this: [start:end:step].

    If we don't pass start its considered 0

    If we don't pass end its considered length of array in that dimension

    If we don't pass step its considered 1


In [ ]:
import numpy as np

x=np.arange(15)

print(f"The values of array are {x}\n")

print(f"The values of x[0] are {x[0]}\n")

print(f"The slice of x[0:10] are {x[0:10]}\n")

The values of array are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

The values of x[0] are 0

The slice of x[0:10] are [0 1 2 3 4 5 6 7 8 9]



##23. Array Iterating   
    
    Iterating means going through elements one by one.

    As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

    If we iterate on a 1-D array it will go through each element one by one.

    In a 2-D array it will go through all the rows.

In [ ]:
#Iterating 1D array

import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
#Iterating 2D array

import numpy as np

narutoComics = np.array([["Naruto", "Hinata", "Shikamaru"], ["Minato","Hiashi","Shikaku "],["Rasengan", "Byakugan", "Shadow Possession"]])

i = 0

for x in narutoComics:

  print(f"Row {i} is {x}")

  i+=1

Row 0 is ['Naruto' 'Hinata' 'Shikamaru']
Row 1 is ['Minato' 'Hiashi' 'Shikaku ']
Row 2 is ['Rasengan' 'Byakugan' 'Shadow Possession']


#24. flatten()

    flatten() function return a copy of the array collapsed into one dimension.

    It is also used to reshape the array
    -------------------------------------------------------------------------------
    Syntax : numpy.ndarray.flatten(order='C')

    -------------
    Parameters :
    -------------
    order : [{'C', 'F', 'A', 'K'}, optional]
    
    'C' means to flatten in row-major (C-style) order.
    
    'F' means to flatten in column-major (Fortran- style)

    -------------------------------------------------------------------------------

In [ ]:
# C style (row) ordering -(Denotes the C programming Language Order)

import numpy as np

narutoComics = np.array([["Naruto", "Hinata", "Shikamaru"], ["Minato","Hiashi","Shikaku "],["Rasengan", "Byakugan", "Shadow Possession"]])

print(narutoComics.flatten())

['Naruto' 'Hinata' 'Shikamaru' 'Minato' 'Hiashi' 'Shikaku ' 'Rasengan'
 'Byakugan' 'Shadow Possession']


In [ ]:
# F style (column) ordering -(Denotes the Fortran programming Language Order)

import numpy as np

narutoComics = np.array([["Naruto", "Hinata", "Shikamaru"], ["Minato","Hiashi","Shikaku "],["Rasengan", "Byakugan", "Shadow Possession"]])

print(narutoComics.flatten(order='F'))

['Naruto' 'Minato' 'Rasengan' 'Hinata' 'Hiashi' 'Byakugan' 'Shikamaru'
 'Shikaku ' 'Shadow Possession']


#25. nditer()

    It is an efficient multidimensional iterator object using which it is possible to iterate over an array.
    
    Each element of an array is visited using Python’s standard Iterator interface.

    

    Points to Note:
    ----------------

    One thing Keep in mind: When we using the nditer object, is that the array which is returned by it is by default read-only.
    
    -------------------------------------------------------------------

    We cannot able to modify the content of the array inside the loop.

    -------------------------------------------------------------------

    This is because it points to the array which is passed as argument to nditer and any changes which will be performed will not be on a copy of the array, but will in fact be to the array itself.

    Ways to Modify the array with nditer:
    --------------------------------------

    To modify the content with nditer, we want to change the array to readwrite mode

    For this use the below syntax:

    np.nditer(arrayName,op_flags=['readwrite']):



In [ ]:
#Normal Iteration of  2D array

import numpy as np

narutoComics = np.array([["Naruto", "Hinata", "Shikamaru"], ["Minato","Hiashi","Shikaku "],["Rasengan", "Byakugan", "Shadow Possession"]])

i = 0

for x in narutoComics:

  print(f"Line {i} is {x}")

  i+=1

Row 0 is ['Naruto' 'Hinata' 'Shikamaru']
Row 1 is ['Minato' 'Hiashi' 'Shikaku ']
Row 2 is ['Rasengan' 'Byakugan' 'Shadow Possession']


In [ ]:
#Iteration with nditer in 2D array

import numpy as np

narutoComics = np.array([["Naruto", "Hinata", "Shikamaru"], ["Minato","Hiashi","Shikaku "],["Rasengan", "Byakugan", "Shadow Possession"]])

i = 0

for x in np.nditer(narutoComics):

  print(f"Line {i} is {x}")

  i+=1

Line 0 is Naruto
Line 1 is Hinata
Line 2 is Shikamaru
Line 3 is Minato
Line 4 is Hiashi
Line 5 is Shikaku 
Line 6 is Rasengan
Line 7 is Byakugan
Line 8 is Shadow Possession


In [ ]:
#Mofify nditer without readwrite op_flag in 2D array

import numpy as np

checkNditer = np.arange(10).reshape(5,2)

print(checkNditer )

for x in np.nditer(checkNditer):

  x[...]=x*x

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: ignored

In [ ]:
#Mofify nditer with readwrite op_flag in 2D array

import numpy as np

checkNditer = np.arange(10).reshape(5,2)

print(checkNditer,"\n")

for x in np.nditer(checkNditer,op_flags=['readwrite']):

  x[...]=x*x

print(f"The square of array is \n {checkNditer}")


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

The square of array is 
 [[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]
 [64 81]]


#26. ravel():

    Ravel function is similar to the flatten function which reduces multi dims array to a single dims array.

    The main difference between both are

    flatten() belongs to an array object and can only be used by NumPy arrays.

    ravel() belongs to NumPy library and can be applied to any object which can be successfully passed.

#27. Transpose T

    The T helps to view the transpose of the array

In [ ]:
import numpy as np

arrayTrans = np.array([["Naruto","Hinata"],["Sasuke","Sakura"],["Shikamaru","Temari"]])

print(arrayTrans,"\n")

print(arrayTrans.T)


[['Naruto' 'Hinata']
 ['Sasuke' 'Sakura']
 ['Shikamaru' 'Temari']] 

[['Naruto' 'Sasuke' 'Shikamaru']
 ['Hinata' 'Sakura' 'Temari']]
